# Generated by Django 3.2.25 on 2024-04-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
